version: '3.9'

services:
  app:
    build:
      args:
        - DEV=true
      context: ./
      dockerfile: Dockerfile
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "1", "--reload", "--log-level", "debug", "app.main:app"]
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - APP_ENV=development
      - GUNICORN_LOG_LEVEL=debug
      - SQLALCHEMY_DATABASE_URI=sqlite:///boardgame.db # or your preferred URI
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
        - .env
        
